### ISSUE TITLE
Data crawling

### ISSUE THREAD

**Issue by ludai0106** [ruoqingsun/ComplexNetwork#1]
**Complete Graph**
- All data within one months: Q, A, timestamp, user ID, reached/badges/reputation.

**Subgraph**
- answers within one month(all answers to the questions asked in the first day)

**Comment by ludai0106** [comment]
@ruoqingsun @liuyiran13 Please leave a comment here for any progress

**Comment by liuyiran13** [comment]
ok

**Comment by ludai0106** [comment]
Data crawling part is officially done! All useful data store in the 'DB' folder.
